name: Continuous Integration

on:
    pull_request:
    push:
        branches:
            - main
            - 'releases/*'

permissions:
    contents: read

jobs:
    test-typescript:
        name: TypeScript Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              id: setup-node
              uses: actions/setup-node@v4
              with:
                  node-version: 18

            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 7
                  run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - uses: actions/cache@v3
              name: Setup pnpm cache
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install Dependencies
              id: npm-ci
              run: pnpm ci

            - name: Check Format
              id: npm-format-check
              run: pnpm run format:check

            - name: Lint
              id: npm-lint
              run: pnpm run lint

            - name: Test
              id: npm-ci-test
              run: pnpm run ci-test

    test-action:
        name: GitHub Actions Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4

            - name: Test Local Action
              id: test-action
              uses: ./
              with:
                  client_id: ${{ secrets.CLIENT_ID }}
                  client_secret: ${{ secrets.CLIENT_SECRET }}
                  region: 'us'
                  realm: 'area-52'
                  name: 'quantumpie'

            - name: Print Output
              id: output
              run: echo "${{ steps.test-action.outputs.json }}"
